module.exports = [
    {
        language: 'spanish',
        text: '*arch*: Mostrar la arquitectura de la máquina (1).\n*uname -m*: Mostrar la arquitectura de la máquina (2).\n*uname -r*: Mostrar la versión del kernel usado.\n*dmidecode -q*: Mostrar los componentes (hardware) del sistema.\n*hdparm -i /dev/hda*: Mostrar las características de un disco duro.\n*hdparm -tT /dev/sda*: Realizar prueba de lectura en un disco duro.\n*cat /proc/cpuinfo*: Mostrar información de la CPU.\n*cat /proc/meminfo*: Verificar el uso de memoria.\n*cat /proc/swaps*: Mostrar ficheros swap.\n*cat /proc/version*: Mostrar la versión del kernel.\n*cat /proc/net/dev*: Mostrar adaptadores de red y estadísticas.\n*cat /proc/mounts*: Mostrar el sistema de ficheros montado.\n*lspci -tv*: Mostrar los dispositivos PCI.\n*lsusb -tv*: Mostrar los dispositivos USB.\n*date*: Mostrar la fecha del sistema.\n*cal 2016*: Mostrar el almanaque de 2016.\n*cal 07 2016*: Mostrar el almanaque para el mes julio de 2016.\n*date 041217002011.00*: Colocar (declarar, ajustar) fecha y hora.\n*clock -w*: Guardar los cambios de fecha en la BIOS.'
    },
    {
        language: 'spanish',
        text: '*shutdown -h now*: apagar el sistema (1).\n*init 0*: apagar el sistema (2).\n*telinit 0*: apagar el sistema (3).\n*halt*: apagar el sistema (4).\n*shutdown -h* _HH:MM_ *&*: apagado planificado del sistema.\n*shutdown -c*: cancelar un apagado planificado del sistema.\n*shutdown -r now*: reiniciar (1).\n*reboot*: reiniciar (2).\n*logout*: cerrar sesión.'
    },
    {
        language: 'spanish',
        text: '<b>cd /home </b>: Entrar en el directorio “home”.\n<b>cd ..</b>: Retroceder un nivel.\n<b>cd ../..</b>: Retroceder 2 niveles.\n<b>cd/</b>: Ir al directorio raíz.\n<b>cd ~</b><i>user</i> : Ir al directorio user.\n<b>cd –</b>: Ir (regresar) al directorio anterior.\n<b>pwd</b>: Mostrar el camino del directorio de trabajo.\n<b>ls</b>: Ver los ficheros de un directorio.\n<b>ls -F</b>: Ver los ficheros de un directorio.\n<b>ls -l</b>: Mostrar los detalles de ficheros y carpetas de un directorio.\n<b>ls -a</b>: Mostrar los ficheros ocultos.\n<b>ls *[0-9]* </b>: Mostrar los ficheros y carpetas que contienen números.\n<b>tree</b>: Mostrar los ficheros y carpetas en forma de árbol comenzando por la raíz.(1)\n<b>lstree</b>: Mostrar los ficheros y carpetas en forma de árbol comenzando por la raíz.(2)\n<b>mkdir dir1</b>: Crear una carpeta o directorio con nombre ‘dir1’.\n<b>mkdir dir1 dir2</b>: Crear dos carpetas o directorios simultáneamente (Crear dos directorios a la vez).\n<b>mkdir -p /tmp/dir1/dir2</b>: Crear un árbol de directorios.\n<b>rm -f file1</b>: Borrar el fichero llamado ‘file1’.\n<b>rmdir dir1</b>: Borrar la carpeta llamada ‘dir1’.\n<b>rm -rf dir1</b>: Eliminar una carpeta llamada ‘dir1’ con su contenido de forma recursiva. (Si lo borro recursivo estoy diciendo que es con su contenido).\n<b>rm -rf dir1 dir2</b>: Borrar dos carpetas (directorios) con su contenido de forma recursiva.\n<b>mv dir1 new_dir</b>: Renombrar o mover un fichero o carpeta (directorio).\n<b>cp file1</b>: Copiar un fichero.\n<b>cp file1 file2</b>: Copiar dos ficheros al unísono.\n<b>cp dir /* .</b>: Copiar todos los ficheros de un directorio dentro del directorio de trabajo actual.\n<b>cp -a /tmp/dir1 .</b>: Copiar un directorio dentro del directorio actual de trabajo.\n<b>cp -a dir1</b>: Copiar un directorio.\n<b>cp -a dir1 dir2</b>: Copiar dos directorio al unísono.\n<b>ln -s file1 lnk1</b>: Crear un enlace simbólico al fichero o directorio.\n<b>ln file1 lnk1</b>: Crear un enlace físico al fichero o directorio.\n<b>touch -t 0712250000 file1</b>: Modificar el tiempo real (tiempo de creación) de un fichero o directorio.\n<b>file file1</b>: Salida (volcado en pantalla) del tipo mime de un fichero texto.\n<b>iconv -l</b>: Listas de cifrados conocidos.\n<b>iconv -f fromEncoding -t toEncoding inputFile > outputFile </b>: Crea una nueva forma del fichero de entrada asumiendo que está codificado en fromEncoding y convirtiéndolo a ToEncoding.\n<b>find . -maxdepth 1 -name *.jpg -print -exec convert ”{}” -resize 80×60 “thumbs/{}” \\; </b>: agrupar ficheros redimensionados en el directorio actual y enviarlos a directorios en vistas de miniaturas (requiere convertir desde ImagemagicK).'
    },
    {
        language: 'spanish',
        text: '<b>find / -name file1</b>: Buscar fichero y directorio a partir de la raíz del sistema.\n<b>find / -user user1</b>: Buscar ficheros y directorios pertenecientes al usuario ‘user1’.\n<b>find /home/user1 -name \\*.bin </b>: buscar ficheros con extensión ‘. bin’ dentro del directorio ‘/ home/user1’.\n<b>find /usr/bin -type f -atime +100</b>: Buscar ficheros binarios no usados en los últimos 100 días.\n<b>find /usr/bin -type f -mtime -10</b>: buscar ficheros creados o cambiados dentro de los últimos 10 días.\n<b>find / -name \\*.rpm -exec chmod 755 ‘{}’ \\;</b>: Buscar ficheros con extensión ‘.rpm’ y modificar permisos.\n<b>find / -xdev -name \\*.rpm</b>: Buscar ficheros con extensión ‘.rpm’ ignorando los dispositivos removibles como cdrom, pen-drive, etc.\n<b>locate \\*.ps</b>: encuentra ficheros con extensión ‘.ps’ ejecutados primeramente con el command ‘updatedb’.\n<b>whereis halt</b>: Mostrar la ubicación de un fichero binario, de ayuda o fuente. En este caso pregunta dónde está el comando ‘halt’.\n<b>which halt</b>: Mostrar la senda completa (el camino completo) a un binario / ejecutable.'
    },
    {
        language: 'spanish',
        text: '<b>mount /dev/hda2 /mnt/hda2</b>: Montar un disco llamado hda2. Verifique primero la existencia del directorio ‘/ mnt/hda2’; si no está, debe crearlo.\n<b>umount /dev/hda2</b>: Desmontar un disco llamado hda2. Salir primero desde el punto ‘/ mnt/hda2.\nfuser -km /mnt/hda2: forzar el desmontaje cuando el dispositivo está ocupado.\n<b>umount -n /mnt/hda2</b>: Correr el desmontaje sin leer el fichero /etc/mtab. Útil cuando el fichero es de solo lectura o el disco duro está lleno.\n<b>mount /dev/fd0 /mnt/floppy</b>: Montar un disco flexible (floppy).\n<b>mount /dev/cdrom /mnt/cdrom</b>: Montar un cdrom / dvdrom.\n<b>mount /dev/hdc /mnt/cdrecorder</b>: Montar un cd regrabable o un dvdrom.\n<b>mount /dev/hdb /mnt/cdrecorder</b>: Montar un cd regrabable / dvdrom (un dvd).\n<b>mount -o loop file.iso /mnt/cdrom</b>: Montar un fichero o una imagen iso.\n<b>mount -t vfat /dev/hda5 /mnt/hda5</b>: Montar un sistema de ficheros FAT32.\n<b>mount /dev/sda1 /mnt/usbdisk</b>: Montar un usb pen-drive o una memoria (sin especificar el tipo de sistema de ficheros).'
    },
    {
        language: 'spanish',
        text: '<b>df -h</b>: Mostrar una lista de las particiones montadas.\n<b>ls -lSr |more</b>: Mostrar el tamaño de los ficheros y directorios ordenados por tamaño.\n<b>du -sh dir1</b>: Estimar el espacio usado por el directorio ‘dir1’.\n<b>du -sk * | sort -rn</b>: Mostrar el tamaño de los ficheros y directorios ordenados por tamaño.\n<b>rpm -q -a –qf ‘%10{SIZE}t%{NAME}n’ | sort -k1,1n</b>: Mostrar el espacio usado por los paquetes rpm instalados organizados por tamaño (Fedora, Redhat y otros).\n<b>dpkg-query -W -f=’${Installed-Size;10}t${Package}n’ | sort -k1,1n</b>: Mostrar el espacio usado por los paquetes instalados, organizados por tamaño (Ubuntu, Debian y otros).'
    },
    {
        language: 'spanish',
        text: '<b>groupadd nombre_del_grupo</b>: Crear un nuevo grupo.\n<b>groupdel nombre_del_grupo</b>: Borrar un grupo.\n<b>groupmod -n nuevo_nombre_del_grupo viejo_nombre_del_grupo</b>: Renombrar un grupo.\n<b>useradd -c “Name Surname ” -g admin -d /home/user1 -s /bin/bash user1</b>: Crear un nuevo usuario perteneciente al grupo “admin”.\n<b>useradd user1</b>: Crear un nuevo usuario.\n<b>userdel -r user1</b>: Borrar un usuario (‘-r’ elimina el directorio Home).\n<b>usermod -c “User FTP” -g system -d /ftp/user1 -s /bin/nologin user1</b>: Cambiar los atributos del usuario.\n<b>passwd</b>: Cambiar contraseña del usuario actual.\n<b>passwd user1</b>: Cambiar la contraseña de un usuario (solamente por root).\n<b>chage -E 2011-12-31 user1</b>: Colocar un plazo para la contraseña del usuario. En este caso dice que la clave expira el 31 de diciembre de 2011.\n<b>pwck</b>: Chequear la sintaxis correcta el formato de fichero de ‘/etc/passwd’ y la existencia de usuarios.\n<b>grpck</b>: Chequear la sintaxis correcta y el formato del fichero ‘/etc/group’ y la existencia de grupos.\n<b>newgrp group_name</b>: Registra a un nuevo grupo para cambiar el grupo predeterminado de los ficheros creados recientemente.'
    },
    {
        language: 'spanish',
        text: '<b>ls -lh</b>: Mostrar permisos.\n<b>ls /tmp | pr -T5 -W$COLUMNS</b>: Dividir la terminal en 5 columnas.\n<b>chmod ugo+rwx directory1</b>: Colocar permisos de lectura ®, escritura (w) y ejecución(x) al propietario (u), al grupo (g) y a otros (o) sobre el directorio ‘directory1’.\n<b>chmod go-rwx directory1</b>: Quitar permiso de lectura ®, escritura (w) y (x) ejecución al grupo (g) y otros (o) sobre el directorio ‘directory1’.\n<b>chown user1 file1</b>: Cambiar el dueño de un fichero.\n<b>chown -R user1 directory1</b>: Cambiar el propietario de un directorio y de todos los ficheros y directorios contenidos dentro.\n<b>chgrp group1 file1</b>: Cambiar grupo de ficheros.\n<b>chown user1:group1 file1</b>: Cambiar usuario y el grupo propietario de un fichero.\n<b>find / -perm -u+s</b>: Visualizar todos los ficheros del sistema con SUID configurado.\n<b>chmod u+s /bin/file1</b>: Colocar el bit SUID en un fichero binario. El usuario que corriendo ese fichero adquiere los mismos privilegios como dueño.\n<b>chmod u-s /bin/file1</b>: Deshabilitar el bit SUID en un fichero binario.\n<b>chmod g+s /home/public</b>: Colocar un bit SGID en un directorio –similar al SUID pero por directorio.\n<b>chmod g-s /home/public</b>: Deshabilitar un bit SGID en un directorio.\n<b>chmod o+t /home/public</b>: Colocar un bit STIKY en un directorio. Permite el borrado de ficheros solamente a los dueños legítimos.\n<b>chmod o-t /home/public</b>: Deshabilitar un bit STIKY en un directorio.'
    },
    {
        language: 'spanish',
        text: '<b>chattr +a file1</b>: Permite escribir abriendo un fichero solamente modo append.\n<b>chattr +c file1</b>: Permite que un fichero sea comprimido / descomprimido automaticamente.\n<b>chattr +d file1</b>: Asegura que el programa ignore borrar los ficheros durante la copia de seguridad.\n<b>chattr +i file1</b>: Convierte el fichero en invariable, por lo que no puede ser eliminado, alterado, renombrado, ni enlazado.\n<b>chattr +s file1</b>: Permite que un fichero sea borrado de forma segura.\n<b>chattr +S file1</b>: Asegura que un fichero sea modificado, los cambios son escritos en modo synchronous como con sync.\n<b>chattr +u file1</b>: Te permite recuperar el contenido de un fichero aún si este está cancelado.\n<b>lsattr</b>: Mostrar atributos especiales.'
    },
    {
        language: 'spanish',
        text: '<b>bunzip2 file1.bz2</b>: Descomprime in fichero llamado ‘file1.bz2’.\n<b>bzip2 file1</b>: Comprime un fichero llamado ‘file1’.\n<b>gunzip file1.gz</b>: Descomprime un fichero llamado ‘file1.gz’.\n<b>gzip file1</b>: Comprime un fichero llamado ‘file1’.\n<b>gzip -9 file1</b>: Comprime con compresión máxima.\n<b>rar a file1.rar test_file</b>: Crear un fichero rar llamado ‘file1.rar’.\n<b>rar a file1.rar file1 file2 dir1</b>: Comprimir ‘file1’, ‘file2’ y ‘dir1’ simultáneamente.\n<b>rar x file1.rar</b>: Descomprimir archivo rar.\n<b>unrar x file1.rar</b>: Descomprimir archivo rar.\n<b>tar -cvf archive.tar file1</b>: Crear un tarball descomprimido.\n<b>tar -cvf archive.tar file1 file2 dir1</b>: Crear un archivo conteniendo ‘file1’, ‘file2′ y’dir1’.\n<b>tar -tf archive.tar</b>: Mostrar los contenidos de un archivo.\n<b>tar -xvf archive.tar</b>: Extraer un tarball.\n<b>tar -xvf archive.tar -C /tmp</b>: Extraer un tarball en / tmp.\n<b>tar -cvfj archive.tar.bz2 dir1</b>: Crear un tarball comprimido dentro de bzip2.\n<b>tar -xvfj archive.tar.bz2</b>: Descomprimir un archivo tar comprimido en bzip2\n<b>tar -cvfz archive.tar.gz dir1</b>: Crear un tarball comprimido en gzip.\n<b>tar -xvfz archive.tar.gz</b>: Descomprimir un archive tar comprimido en gzip.\n<b>zip file1.zip file1</b>: Crear un archivo comprimido en zip.\n<b>zip -r file1.zip file1 file2 dir1</b>: Comprimir, en zip, varios archivos y directorios de forma simultánea.\n<b>unzip file1.zip</b>: Descomprimir un archivo zip.'
    },
    {
        language: 'spanish',
        text: '<b>rpm -ivh package.rpm</b>: Instalar un paquete rpm.\n<b>rpm -ivh –nodeeps package.rpm</b>: Instalar un paquete rpm ignorando las peticiones de dependencias.\n<b>rpm -U package.rpm</b>: Actualizar un paquete rpm sin cambiar la configuración de los ficheros.\n<b>rpm -F package.rpm</b>: Actualizar un paquete rpm solamente si este está instalado.\n<b>rpm -e package_name.rpm</b>: Eliminar un paquete rpm.\n<b>rpm -qa</b>: Mostrar todos los paquetes rpm instalados en el sistema.\n<b>rpm -qa | grep httpd</b>: Mostrar todos los paquetes rpm con el nombre “httpd”.\n<b>rpm -qi package_name</b>: Obtener información en un paquete específico instalado.\n<b>rpm -qg “System Environment/Daemons”</b>: Mostar los paquetes rpm de un grupo software.\n<b>rpm -ql package_name</b>: Mostrar lista de ficheros dados por un paquete rpm instalado.\n<b>rpm -qc package_name</b>: Mostrar lista de configuración de ficheros dados por un paquete rpm instalado.\n<b>rpm -q package_name –whatrequires</b>: Mostrar lista de dependencias solicitada para un paquete rpm.\n<b>rpm -q package_name –whatprovides</b>: Mostar la capacidad dada por un paquete rpm.\n<b>rpm -q package_name –scripts</b>: Mostrar los scripts comenzados durante la instalación /eliminación.\n<b>rpm -q package_name –changelog</b>: Mostar el historial de revisions de un paquete rpm.\n<b>rpm -qf /etc/httpd/conf/httpd.conf</b>: Verificar cuál paquete rpm pertenece a un fichero dado.\n<b>rpm -qp package.rpm -l</b>: Mostrar lista de ficheros dados por un paquete rpm que aún no ha sido instalado.\n<b>rpm –import /media/cdrom/RPM-GPG-KEY</b>: Importar la firma digital de la llave pública.\n<b>rpm –checksig package.rpm</b>: Verificar la integridad de un paquete rpm.\n<b>rpm -qa gpg-pubkey</b>: Verificar la integridad de todos los paquetes rpm instalados.\n<b>rpm -V package_name</b>: Chequear el tamaño del fichero, licencias, tipos, dueño, grupo, chequeo de resumen de MD5 y última modificación.\n<b>rpm -Va</b>: Chequear todos los paquetes rpm instalados en el sistema. Usar con cuidado.\n<b>rpm -Vp package.rpm</b>: Verificar un paquete rpm no instalado todavía.\n<b>rpm2cpio package.rpm | cpio –extract –make-directories *bin*</b>: Extraer fichero ejecutable desde un paquete rpm.\n<b>rpm -ivh /usr/src/redhat/RPMS/`arch`/package.rpm</b>: Instalar un paquete construido desde una fuente rpm.\n<b>rpmbuild –rebuild package_name.src.rpm</b>: Construir un paquete rpm desde una fuente rpm.'
    },
    {
        language: 'spanish',
        text: '<b>yum install package_name</b>: Descargar e instalar un paquete rpm.\n<b>yum localinstall package_name.rpm</b>: Este instalará un RPM y tratará de resolver todas las dependencies para ti, usando tus repositorios.\n<b>yum update package_name.rpm</b>: Actualizar todos los paquetes rpm instalados en el sistema.\n<b>yum update package_name</b>: Modernizar / actualizar un paquete rpm.\n<b>yum remove package_name</b>: Eliminar un paquete rpm.\n<b>yum list</b>: Listar todos los paquetes instalados en el sistema.\n<b>yum search package_name</b>: Encontrar un paquete en repositorio rpm.\n<b>yum clean packages</b>: Limpiar un caché rpm borrando los paquetes descargados.\n<b>yum clean headers</b>: Eliminar todos los ficheros de encabezamiento que el sistema usa para resolver la dependencia.\n<b>yum clean all</b>: Eliminar desde los paquetes caché y ficheros de encabezado.'
    },
    {
        language: 'spanish',
        text: '<b>dpkg -i package.deb</b>: Instalar / actualizar un paquete deb.\n<b>dpkg -r package_name</b>: Eliminar un paquete deb del sistema.\n<b>dpkg -l</b>: Mostrar todos los paquetes deb instalados en el sistema.\n<b>dpkg -l | grep httpd</b>: Mostrar todos los paquetes deb con el nombre “httpd”\n<b>dpkg -s package_name</b>: Obtener información en un paquete específico instalado en el sistema.\n<b>dpkg -L package_name</b>: Mostar lista de ficheros dados por un paquete instalado en el sistema.\n<b>dpkg –contents package.deb</b>: Mostrar lista de ficheros dados por un paquete no instalado todavía.\n<b>dpkg -S /bin/ping</b>: Verificar cuál paquete pertenece a un fichero dado.'
    },
    {
        language: 'spanish',
        text: '<b>apt-get install package_name</b>: Instalar / actualizar un paquete deb.\n<b>apt-cdrom install package_name</b>: Instalar / actualizar un paquete deb desde un cdrom.\n<b>apt-get update</b>: Actualizar la lista de paquetes.\n<b>apt-get upgrade</b>: Actualizar todos los paquetes instalados.\n<b>apt-get remove package_name</b>: Eliminar un paquete deb del sistema.\n<b>apt-get check</b>: Verificar la correcta resolución de las dependencias.\n<b>apt-get clean</b>: Limpiar cache desde los paquetes descargados.\n<b>apt-cache search searched-package</b>: Retorna lista de paquetes que corresponde a la serie «paquetes buscados».'
    },
	{
        language: 'spanish',
        text: '<b>cat file1</b>: Ver los contenidos de un fichero comenzando desde la primera hilera.\n<b>tac file1</b>: Ver los contenidos de un fichero comenzando desde la última línea.\n<b>more file1</b>: Ver el contenido a lo largo de un fichero.\n<b>less file1</b>: Parecido al commando ‘more’ pero permite salvar el movimiento en el fichero así como el movimiento hacia atrás.\n<b>head -2 file1</b>: Ver las dos primeras líneas de un fichero.\n<b>tail -2 file1</b>: Ver las dos últimas líneas de un fichero.\n<b>tail -f /var/log/messages</b>: Ver en tiempo real qué ha sido añadido al fichero.'
    },
    {
        language: 'spanish',
        text: '*cat file1 file2 .. | command <> file1_in.txt_or_file1_out.txt*: Sintaxis general para la manipulación de texto utilizando PIPE, STDIN y STDOUT.\n*cat file1 | command( sed, grep, awk, grep, etc…) > result.txt*: Sintaxis general para manipular un texto de un fichero y escribir el resultado en un fichero nuevo.\n*cat file1 | command( sed, grep, awk, grep, etc…) » result.txt*: Sintaxis general para manipular un texto de un fichero y añadir resultado en un fichero existente.\n*grep Aug /var/log/messages*: Buscar palabras “Aug” en el fichero ‘/var/log/messages’.\n*grep ^Aug /var/log/messages*: Buscar palabras que comienzan con “Aug” en fichero ‘/var/log/messages’\n*grep [0-9] /var/log/messages*: Seleccionar todas las líneas del fichero ‘/var/log/messages’ que contienen números.\n*sed ‘s/stringa1/stringa2/g’ example.txt*: Reubicar “string1” con “string2” en ejemplo.txt\n*sed ‘/^$/d’ example.txt*: Eliminar todas las líneas en blanco desde el ejemplo.txt\n*echo ‘esempio’ | tr ‘[:lower:]’ ‘[:upper:]’*: Convertir minúsculas en mayúsculas.\n*sed -e ‘1d’ result.txt*: Elimina la primera línea del fichero ejemplo.txt\n*sed -n ‘/stringa1/p’*: Visualizar solamente las líneas que contienen la palabra “string1”.\n'
    },
    {
        language: 'spanish',
        text: '*dos2unix filedos.txt fileunix.txt*: Convertir un formato de fichero texto desde MSDOS a UNIX.\n*unix2dos fileunix.txt filedos.txt*: Convertir un formato de fichero de texto desde UNIX a MSDOS.\n*recode ..HTML < page.txt > page.html*: Convertir un fichero de texto en html.\n*recode -l | more*: mostrar todas las conversiones de formato disponibles.'
    },
    {
        language: 'spanish',
        text: '*badblocks -v /dev/hda1*: Chequear los bloques defectuosos en el disco hda1.\n*fsck /dev/hda1*: Reparar / chequear la integridad del fichero del sistema Linux en el disco hda1.\n*fsck.ext2 /dev/hda1*: Reparar / chequear la integridad del fichero del sistema ext 2 en el disco hda1.\n*e2fsck /dev/hda1*: Reparar / chequear la integridad del fichero del sistema ext 2 en el disco hda1.\n*e2fsck -j /dev/hda1*: Reparar / chequear la integridad del fichero del sistema ext 3 en el disco hda1.\n*fsck.ext3 /dev/hda1*: Reparar / chequear la integridad del fichero del sistema ext 3 en el disco hda1.\n*fsck.vfat /dev/hda1*: Reparar / chequear la integridad del fichero sistema fat en el disco hda1.\n*fsck.msdos /dev/hda1*: Reparar / chequear la integridad de un fichero del sistema dos en el disco hda1.\n*dosfsck /dev/hda1*: Reparar / chequear la integridad de un fichero del sistema dos en el disco hda1.'
    },
    {
        language: 'spanish',
        text: '*mkfs /dev/hda1*: Crear un fichero de sistema tipo Linux en la partición hda1.\n*mke2fs /dev/hda1*: Crear un fichero de sistema tipo Linux ext 2 en hda1.\n*mke2fs -j /dev/hda1*: Crear un fichero de sistema tipo Linux ext3 (periódico) en la partición hda1.\n*mkfs -t vfat 32 -F /dev/hda1*: Crear un fichero de sistema FAT32 en hda1.\n*fdformat -n /dev/fd0*: Formatear un disco flooply.\n*mkswap /dev/hda3*: Crear un fichero de sistema swap.'
    },
    {
        language: 'spanish',
        text: '*mkswap /dev/hda3*: Crear fichero de sistema swap.\n*swapon /dev/hda3*: Activando una nueva partición swap.\n*swapon /dev/hda2 /dev/hdb3*: Activar dos particiones swap.'
    },
    {
        language: 'spanish',
        text: '<b>dump -0aj -f /tmp/home0.bak /home</b>: Hacer una salva completa del directorio ‘/home’.\n<b>dump -1aj -f /tmp/home0.bak /home</b>: Hacer una salva incremental del directorio ‘/home’.\n<b>restore -if /tmp/home0.bak</b>: Restaurando una salva interactivamente.\n<b>rsync -rogpav –delete /home /tmp</b>: Sincronización entre directorios.\n<b>rsync -rogpav -e ssh –delete /home ip_address:/tmp</b>: Rsync a través del túnel SSH.\n<b>rsync -az -e ssh –delete ip_addr:/home/public /home/local</b>: Sincronizar un directorio local con un directorio remoto a través de ssh y de compresión.\n<b>rsync -az -e ssh –delete /home/local ip_addr:/home/public</b>: Sincronizar un directorio remoto con un directorio local a través de ssh y de compresión.\n<b>dd bs=1M if=/dev/hda | gzip | ssh user@ip_addr ‘dd of=hda.gz’</b>: Hacer una salva de un disco duro en un host remoto a través de ssh.\n<b>dd if=/dev/sda of=/tmp/file1</b>: Salvar el contenido de un disco duro a un fichero. (En este caso el disco duro es “sda” y el fichero “file1”).\n<b>tar -Puf backup.tar /home/user</b>: Hacer una salva incremental del directorio ‘/home/user’.\n<b>( cd /tmp/local/ && tar c . ) | ssh -C user@ip_addr ‘cd /home/share/ && tar x -p’</b>: Copiar el contenido de un directorio en un directorio remoto a través de ssh.\n<b>( tar c /home ) | ssh -C user@ip_addr ‘cd /home/backup-home && tar x -p’</b>: Copiar un directorio local en un directorio remoto a través de ssh.\n<b>tar cf – . | (cd /tmp/backup ; tar xf – )</b>: Copia local conservando las licencias y enlaces desde un directorio a otro.\n<b>find /home/user1 -name ‘*.txt’ | xargs cp -av –target-directory=/home/backup/ –parents</b>: Encontrar y copiar todos los ficheros con extensión ‘.txt’ de un directorio a otro.\n<b>dd if=/dev/hda of=/dev/fd0 bs=512 count=1</b>: Hacer una copia del MRB (Master Boot Record) a un disco floppy.\n<b>dd if=/dev/fd0 of=/dev/hda bs=512 count=1</b>: Restaurar la copia del MBR (Master Boot Record) salvada en un floppy.'
    },
    {
        language: 'spanish',
        text: '*cdrecord -v gracetime=2 dev=/dev/cdrom -eject blank=fast -force*: Limpiar o borrar un cd regrabable.\n*mkisofs /dev/cdrom > cd.iso*: Crear una imagen iso de cdrom en disco.\n*mkisofs /dev/cdrom | gzip > cd_iso.gz*: Crear una imagen comprimida iso de cdrom en disco.\n*mkisofs -J -allow-leading-dots -R -V “Label CD” -iso-level 4 -o ./cd.iso data_cd*: Crear una imagen iso de un directorio.\n*cdrecord -v dev=/dev/cdrom cd.iso*: Quemar una imagen iso.\n*gzip -dc cd_iso.gz | cdrecord dev=/dev/cdrom –*: Quemar una imagen iso comprimida.\n*mount -o loop cd.iso /mnt/iso*: Montar una imagen iso.\n*cd-paranoia -B*: Llevar canciones de un cd a ficheros wav.\n*cd-paranoia – ”-3”*: Llevar las 3 primeras canciones de un cd a ficheros wav.\n*cdrecord –scanbus*: Escanear bus para identificar el canal scsi.\n*dd if=/dev/hdc | md5sum*: Hacer funcionar un md5sum en un dispositivo, como un CD.'
    },
    {
        language: 'spanish',
        text: '*ifconfig eth0*: Mostrar la configuración de una tarjeta de red Ethernet.\n*ifup eth0*: Activar una interface ‘eth0’.\n*ifdown eth0*: Deshabilitar una interface ‘eth0’.\n*ifconfig eth0 192.168.1.1 netmask 255.255.255.0*: Configurar una dirección IP.\n*ifconfig eth0 promisc*: Configurar ‘eth0’en modo común para obtener los paquetes (sniffing).\n*dhclient eth0*: Activar la interface ‘eth0’ en modo dhcp.\n*route -n*: Mostrar mesa de recorrido.\n*route add -net 0/0 gw IP_Gateway*: Configurar entrada predeterminada.\n*route add -net 192.168.0.0 netmask 255.255.0.0 gw 192.168.1.1*: Configurar ruta estática para buscar la red ‘192.168.0.0/16’.\n*route del 0/0 gw IP_gateway*: Eliminar la ruta estática.\n*echo “1” > /proc/sys/net/ipv4/ip_forward*: Activar el recorrido ip.\n*hostname*: Mostrar el nombre del host del sistema.\n*host www.example.com*: Buscar el nombre del host para resolver el nombre a una dirección ip(1).\n*nslookup www.example.com*: Buscar el nombre del host para resolver el nombre a una direccióm ip y viceversa(2).\n*ip link show*: Mostar el estado de enlace de todas las interfaces.\n*mii-tool eth0*: Mostar el estado de enlace de ‘eth0’.\n*ethtool eth0*: Mostrar las estadísticas de tarjeta de red ‘eth0’.\n*netstat -tup*: Mostrar todas las conexiones de red activas y sus PID.\n*netstat -tupl*: Mostrar todos los servicios de escucha de red en el sistema y sus PID.\n*tcpdump tcp port 80*: Mostrar todo el tráfico HTTP.\n*iwlist scan*: Mostrar las redes inalámbricas.\n*iwconfig eth1*: Mostrar la configuración de una tarjeta de red inalámbrica.\n*whois www.example.com*: Buscar en base de datos Whois.'
    },
    {
        language: 'spanish',
        text: '*nbtscan ip_addr*: Resolución de nombre de red bios.\n*nmblookup -A ip_addr*: Resolución de nombre de red bios.\n*smbclient -L ip_addr/hostname*: Mostrar acciones remotas de un host en windows.'
    },
    {
        language: 'spanish',
        text: '*iptables -t filter -L*: Mostrar todas las cadenas de la tabla de filtro.\n*iptables -t nat -L*: Mostrar todas las cadenas de la tabla nat.\n*iptables -t filter -F*: Limpiar todas las reglas de la tabla de filtro.\n*iptables -t nat -F*: Limpiar todas las reglas de la tabla nat.\n*iptables -t filter -X*: Borrar cualquier cadena creada por el usuario.\n*iptables -t filter -A INPUT -p tcp –dport telnet -j ACCEPT*: Permitir las conexiones telnet para entar.\n*iptables -t filter -A OUTPUT -p tcp –dport http -j DROP*: Bloquear las conexiones HTTP para salir.\n*iptables -t filter -A FORWARD -p tcp –dport pop3 -j ACCEPT*: Permitir las conexiones POP a una cadena delantera.\n*iptables -t filter -A INPUT -j LOG –log-prefix “DROP INPUT”*: Registrando una cadena de entrada.\n*iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE*: Configurar un PAT (Puerto de traducción de dirección) en eth0, ocultando los paquetes de salida forzada.\n*iptables -t nat -A PREROUTING -d 192.168.0.1 -p tcp -m tcp –dport 22 -j DNAT –to-destination 10.0.0.2:22*: Redireccionar los paquetes diriguidos de un host a otro.\n'
    },
    {
        language: 'spanish',
        text: '*top*: Mostrar las tareas de linux usando la mayoría cpu.\n*ps -eafw*: Muestra las tareas Linux.\n*ps -e -o pid,args –forest*: Muestra las tareas Linux en un modo jerárquico.\n*pstree*: Mostrar un árbol sistema de procesos.\n*kill -9 ID_Processo*: Forzar el cierre de un proceso y terminarlo.\n*kill -1 ID_Processo*: Forzar un proceso para recargar la configuración.\n*lsof -p $$*: Mostrar una lista de ficheros abiertos por procesos.\n*lsof /home/user1*: Muestra una lista de ficheros abiertos en un camino dado del sistema.\n*strace -c ls >/dev/null*: Mostrar las llamadas del sistema hechas y recibidas por un proceso.\n*strace -f -e open ls >/dev/null*: Mostrar las llamadas a la biblioteca.\n*watch -n1 ‘cat /proc/interrupts’*: Mostrar interrupciones en tiempo real.\n*last reboot*: Mostrar historial de reinicio.\n*lsmod*: Mostrar el kernel cargado.\n*free -m*: Muestra el estado de la RAM en megabytes.\n*smartctl -A /dev/hda*: Monitorear la fiabilidad de un disco duro a través de SMART.\n*smartctl -i /dev/hda*: Chequear si SMART está activado en un disco duro.\n*tail /var/log/dmesg*: Mostrar eventos inherentes al proceso de carga del kernel.\n*tail /var/log/messages*: Mostrar los eventos del sistema.'
    },
    {
        language: 'spanish',
        text: '*apropos PALABRA CLAVE*: Mostrar una lista de comandos que pertenecen a las palabras claves de un programa; son útiles cuando tú sabes qué hace tu programa, pero desconoces el nombre del comando.\n*man ping*: Mostrar las páginas del manual on-line; por ejemplo, en un comando ping, usar la opción ‘-k’ para encontrar cualquier comando relacionado.\n*whatis PALABRA CLAVE*: Muestra la descripción de lo que hace el programa.\n*mkbootdisk –device /dev/fd0 `uname -r`*: Crear un floppy boteable.\n*gpg -c file1*: Codificar un fichero con guardia de seguridad GNU.\n*gpg file1.gpg*: Decodificar un fichero con Guardia de seguridad GNU.\n*wget -r www.example.com*: Descargar un sitio web completo.\n*wget -c www.example.com/file.iso*: Descargar un fichero con la posibilidad de parar la descargar y reanudar más tarde.\n*echo ‘wget -c www.example.com/files.iso‘ | at 09:00*: Comenzar una descarga a cualquier hora. En este caso empezaría a las 9 horas.\n*ldd /usr/bin/ssh*: Mostrar las bibliotecas compartidas requeridas por el programa ssh.\n*alias hh=’history’*: Colocar un alias para un commando –hh= Historial.\n*chsh*: Cambiar el comando Shell.\n*chsh –list-shells*: Es un comando adecuado para saber si tienes que hacer remoto en otra terminal.\n*who -a*: Mostrar quien está registrado, e imprimir hora del último sistema de importación, procesos muertos, procesos de registro de sistema, procesos activos producidos por init, funcionamiento actual y últimos cambios del reloj del sistema.'
    }
];